-- MOSTRAR A QUANTIDADE DE FUNCIONARIOS NA TABELA EMPLOYEES
SET SERVEROUTPUT ON
DECLARE
VCOUNT INTEGER;
BEGIN
-- RECUPERAR A QUANTIDADE DE FUNCIONARIOS CADASTRADOS
SELECT COUNT(*)
INTO
VCOUNT
FROM HR.EMPLOYEES;
-- IMPRIMIR NA TELA A QUANTIDADE DE FUNCIONARIOS CADASTRADOS
DBMS_OUTPUT.PUT_LINE('EXISTEM: '||TO_CHAR(VCOUNT)||' FUNCIONARIOS CADASTRADOS');
EXCEPTION
/*SE OCORRER QUALQUER ERRO, INFORMAR O USUARIO QUE NÃO FOI POSSIVEL VERIFICAR A QUANTIDADE DE PRODUTOS CADASTRADOS */
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('NÃO FOI POSSIVEL CONFIMAR A QUANTIDADE DE FUNCIONARIOS CADASTRADOS');
END;

-- EXEMPLO PRINT DE DATA
DECLARE
    VHOJE DATE DEFAULT SYSDATE;
BEGIN
    --IMPRIME A DATA
    DBMS_OUTPUT.PUT_LINE('HOJE É '||VHOJE);
END;


DECLARE
    VHOJE DATE DEFAULT SYSDATE;
    VNASC DATE :='26/01/1998';
    V_DIAS INT;
BEGIN
V_DIAS:=VHOJE-VNASC;
DBMS_OUTPUT.PUT_LINE('Você possui: '||V_DIAS||' Dias de vida');
END;