SET SERVEROUTPUT ON

-- DECLARAÇÃO DE VARIAVEL
DECLARE

V_IDFUNC HR.EMPLOYEES.ID_FUNC%TYPE;
V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE;
V_SALARIO HR.EMPLOYEES.SALARY%TYPE;

-- DECLARAÇÃO DE CURSORES

CURSOR CS_TOP_10 IS
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
    FROM HR.EMPLOYEES A
    ORDER BY SALARY DESC;

BEGIN

-- ABRE CURSOR SE AINDA NÃO TIVER ABERTO
IF NOT CS_TOP_10%ISOPEN THEN
OPEN CS_TOP_10;
END IF;

-- EXECUTA UM LOOP COM 10 CICLOS.
FOR I IN 1..10 LOOP

-- EXTRAI DADOS O REGISTRO CORRENTE DO CUJRSOR E AVANÇAR PARA O PROXIMO

