DECLARE
-- DECLARAÇÃO DE CURSORES
CURSOR CS_FUNC(PMENOR NUMBER, PMAIOR NUMBER) IS
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM HR.EMPLOYEES A
WHERE A.SALARY BETWEEN PMENOR AND PMAIOR
ORDER BY A.SALARY DESC;

BEGIN

--ABRE CURSOR PARA FUNCIONARIOS COM SALARIO ENTRE 1000 E 9999
DBMS_OUTPUT.PUT_LINE('FUNCIONARIOS COM MÉDIA ENTRE 1000 E 9999');
FOR RFUNC IN CS_FUNC(1000,9999) LOOP
-- IMPRIME NA TELA OS FUNCIONARIOS COM SALARIO NO INTERVALO DE 1000 E 9999
DBMS_OUTPUT.PUT_LINE(RFUNC.EMPLOYEE_ID||' - '||RFUNC.FIRST_NAME||' - '||RFUNC.SALARY);
END LOOP;

--ABRE CURSOR PARA FUNCIONARIOS COM SALARIO ENTRE 10000 E 19000
DBMS_OUTPUT.PUT_LINE('FUNCIONARIOS COM MÉDIA ENTRE 10000 E 19000');
FOR RFUNC IN CS_FUNC(10000,19000) LOOP
-- IMPRIME NA TELA OS FUNCIONARIOS COM SALARIO NO INTERVALO DE 10000 E 19000
DBMS_OUTPUT.PUT_LINE(RFUNC.EMPLOYEE_ID||' - '||RFUNC.FIRST_NAME||' - '||RFUNC.SALARY);
END LOOP;
END;