SET SERVEROUTPUT ON
DECLARE
-- DECLARAÇÃO DE VARIAVEIS
V_IDFUNC HR.employees.EMPLOYEE_ID%TYPE;
V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE;
V_SALARIO HR.EMPLOYEES.SALARY%TYPE;

-- DECLARAÇÃO DE CURSORES

CURSOR CS_SALARIO_TOP_10 IS
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
    FROM HR.EMPLOYEES A
    ORDER BY A.SALARY DESC;

BEGIN

-- ABRE CURSOR

OPEN CS_SALARIO_TOP_10;

-- EXECUTA UM LOOP COM 10 CICLOS.
FOR i IN 1..10 LOOP

--EXTRAI DADOS O REGISTRO CORRENTE DO CURSOR E AVANÇA PARA O PROXIMO.
FETCH CS_SALARIO_TOP_10 INTO V_IDFUNC, V_NOME, V_SALARIO;

-- IMPRIME OS DADOS EXTRAIDOS NA TELA.
DBMS_OUTPUT.PUT_LINE(V_IDFUNC||' - '||V_NOME||' - '||V_SALARIO);
--FECHA O LOOP
END LOOP;

--FECHA CURSOR
close cs_salario_top_10;