SET SERVEROUTPUT ON
DECLARE
--DECLARAÇÃO DE VARIAVEIS
V_IDFUNC    HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
V_NOME      HR.EMPLOYEES.FIRST_NAME%TYPE;
V_SALARIO   HR.EMPLOYEES.SALARY%TYPE;

-- DECLARAÇÃO DE CURSORES.
CURSOR CS_SALARIO_TOP_10 IS
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
    FROM HR.EMPLOYEES A
    ORDER BY A.SALARY DESC;
BEGIN
--ABRE O CURSOR
OPEN CS_SALARIO_TOP_10;
-- EXECUTA UM LOOP COM 10 CICLOS
FROM I IN 1..10 LOOP
-- EXTRAI DADOS O REGISTRO CORRENTE DO CURSOR E AVANÇA PARA O PROXIMO
FETCH CS_SALARIO_TOP_10 INTO V_IDFUNC, V_NOME, ID_SALARIO;
-- IMPRIME DADOS EXTRAIDOS NA TELA
DBMS_OUTPUT.PUT_LINE(V_IDFUNC||' - '||V_NOME||' - '||V_SALARIO);
END LOOP;
-- FECHA CURSOR
CLO
