--CURSOR IMPLICITO ORACLE
SET SERVEROUTPUT ON

BEGIN
--INICIA O LOOP EM CONJUNTO ATIVO DO CURSOR
FOR VFUNC IN    (SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
                FROM HR.EMPLOYEES A
                ORDER BY A.SALARY DESC)

LOOP
-- IMPRIME OS DADOS EXTRAIDOS NA TELA
DBMS_OUTPUT.PUT_LINE(VFUNC.EMPLOYEE_ID||' - '||VFUNC.FIRST_NAME||' - '||VFUNC.SALARY);
END LOOP;
END;
