SET SERVEROUTPUT ON
-- DECLARAÇÃO DA VARIAVEL
DECLARE

V_IDFUNC HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE;
V_SALARIO HR.EMPLOYEES.SALARY%TYPE;
V_POSICAO INT DEFAULT 0;

--CRIAÇÃO DO CURSOR
CURSOR CS_SALARIO IS
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
    FROM HR.EMPLOYEES A
    ORDER BY SALARY DESC;
    
BEGIN
-- IF PARA CASO O CURSOR NÃO ESTIVER ABERTO, ABRI-LO
IF NOT CS_SALARIO%ISOPEN THEN
OPEN CS_SALARIO;
END IF;
-- CRIA O LOOP
LOOP
-- EXTRAI DADOS O REGISTRO CORRENTE DO CURSOR E AVANÇA PARA O PROXIMO.
FETCH CS_SALARIO INTO V_IDFUNC, V_NOME, V_SALARIO;
-- SAI DO LOOP QUANDO NÃO TIVER MAIS REGISTROS PARA PROCESSAR
EXIT WHEN CS_SALARIO%NOTFOUND;
-- IMPRIME DADOS EXTRAIDOS NA TELA
V_POSICAO:=V_POSICAO+1;
DBMS_OUTPUT.PUT_LINE(V_POSICAO||' - '||V_IDFUNC||' - '||V_NOME||' - '||V_SALARIO);
END LOOP;
--FECHA O CURSOR
CLOSE CS_SALARIO;
END;