--Parte 1 CONCEDE-GRANT
--Criar um login 'ALUNO' para dar permissões no banco e objetos
SELECT USER FROM DUAL;
-- CONCEDENDO ACESSO DE ATUALIZAÇÃO PARA ALUNO
GRANT UPDATE ON ALUNO.FUNCIONARIOS TO ALUNO;
--CONCEDENDO ACESSO DE ATUALIZAÇÃO PARA ALUNO COM WITH ADMIN OPTION
--USUARIO ALUNO PODE ESTENDER SEUS PRIVILEGIOS DE SISTEMA PARA OUTRPS USUARIOS
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO ALUNO WITH ADMIN OPTION;
--CONCENDENDO ACESSO DE UPDATE, SELECT PARA ALUNO NA TABELA SENSO
GRANT SELECT, UPDATE ON ALUNO.SENSO TO ALUNO;
--CONCEDENDO ACESSO DE INSERT, DELETE PARA PARA ALUNO NA TABELA SENSO
GRANT INSERT, DELETE ON ALUNO.SENSO TO ALUNO;
--CONCEDENDO ACESSO DE CRIAÇÃO DE PROCEDURE E VIEW PARA ALUNO EM TODOS OBJETOS
GRANT CREATE PROCEDURE, CREATE VIEW TO ALUNO;
-- DICA PARA GERAR GRANTS PARA MUITOS OBJETOS;
SELECT 'GRANT ALL ON ' ||OWNER|| '.' || table_name || ' TO ALUNO;' AS RETORNO, tablespace_name
FROM DBA_TABLES
WHERE tablespace_name = 'CURSO';

SELECT * FROM DBA_TABLES WHERE TABLESPACE_NAME LIKE '%O%';


GRANT ALL ON ALUNO.SENSO TO ALUNO;
GRANT ALL ON ALUNO.UF TO ALUNO;
GRANT ALL ON ALUNO.FUNCIONARIOS TO ALUNO;
GRANT ALL ON ALUNO.FUNCIONARIO TO ALUNO;
GRANT ALL ON ALUNO.AUDIT_SALARIO TO ALUNO;
GRANT ALL ON ALUNO.TMP_FUNCIONARIOS TO ALUNO;



SELECT * FROM DBA_TABLES WHERE OWNER = 'ALUNO';

SELECT 'GRANT UPDATE ON ' || object_name || ' TO ALUNO;' AS RETORNO
FROM user_objects
where object_type='TABLE';

SELECT TABLESPACE_NAME, TABLE_NAME, OWNER FROM DBA_TABLES
WHERE Owner = 'ALUNO';

--EXEMPLO
GRANT UPDATE ON HELP TO ALUNO;

-- CONCEDENDO ACESSO DE DELETE PARA ALUNO NA TABELA SENSO
GRANT DELETE ON ALUNO.SENSO TO ALUNO;


-- CONCENDENDO ACESSO A DETERMINADOS CAMPOS EM UMA TABELA PARA ALUNO
GRANT INSERT, UPDATE (NOME, SETOR) ON ALUNO.FUNCIONARIOS TO ALUNO;

--CONCENDENDO ACESSO PARA EXECUTAR A PROC proc_quadrado PARA ALUNO
GRANT EXECUTE ON ALUNO.proc_quadrado TO ALUNO;

-- CHECKANDO TODOS ACESSOS A TODOS OBJETOS PARA ALUNO
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE 'ALUNO';

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE LIKE 'ALUNO';

SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE = 'ALUNO';



