SET SERVEROUTPUT ON
<<BLOCOPRINCIPAL>> -- DECLARAÇÃO DE BLOCO PRINCIPAL

DECLARE
VNUM1 NUMBER := 100;
BEGIN
DECLARE
VNUM1 NUMBER := 50;
BEGIN
DBMS_OUTPUT.PUT_LINE('IMPRESSÃO 1: '||BLOCOPRINCIPAL.VNUM1);
DBMS_OUTPUT.PUT_LINE('IMPRESSÃO 2: '||VNUM1);
END;
DBMS_OUTPUT.PUT_LINE('IMPRESSÃO 3: '||VNUM1);
END;

-- OUTRO EXEMPLO
DECLARE V_TEMP NUMBER := 100;
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_TEMP);
    DECLARE V_TEMP NUMBER := 200;
    BEGIN
        DBMS_OUTPUT.PUT_LINE(V_TEMP);
    END;
    DBMS_OUTPUT.PUT_LINE(V_TEMP);
END;