-- sem parametros, ou seja, com o funcionario já definido, sem parametro para definirmos depois.
CREATE OR REPLACE FUNCTION FN_NOME
    RETURN VARCHAR IS
    V_NOME VARCHAR(20);
BEGIN
    SELECT A.FIRST_NAME
    INTO V_NOME
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID = 100;
    
    RETURN V_NOME;
END;

-- SELECIONAR A FUNÇÃO
SELECT FN_NOME FROM DUAL;

-- COM PARAMETROS
CREATE OR REPLACE FUNCTION FN_NOME2(P_ID IN NUMBER)
    RETURN VARCHAR IS
    V_NOME VARCHAR(15);
BEGIN
    SELECT A.FIRST_NAME
    INTO V_NOME
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID=P_ID;
    
    RETURN V_NOME;
END;

-- SELECIONAR A FUNÇÃO
SELECT FN_NOME2(101) AS FUNCIONARIO FROM DUAL;