-- SEM PARAMETROS
CREATE OR REPLACE FUNCTION FN_NOME
RETURN VARCHAR IS
V_NOME VARCHAR(20);
BEGIN
    SELECT A.FIRST_NAME
    INTO V_NOME
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID = 100;
    
    RETURN V_NOME;
END;

SELECT FN_NOME FROM DUAL;

/

-- COM PARAMETROS
 CREATE OR REPLACE FUNCTION FN_NOME2(P_ID IN NUMBER)
 RETURN VARCHAR IS
 V_NOME VARCHAR(20);
 BEGIN
    SELECT A.FIRST_NAME
    INTO V_NOME
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID = P_ID;
    
    RETURN V_NOME;
    
END;

SELECT FN_NOME2(101) FROM DUAL;

/

-- FUNCTION SIMULA AUMENTO

CREATE OR REPLACE FUNCTION FN_AUMENTO (P_PCT IN NUMBER, P_ID_FUNC IN NUMBER)
RETURN NUMBER IS
V_NOVO_SAL NUMBER;
BEGIN
    SELECT ((A.SALARY/100)*P_PCT)+A.SALARY
    INTO V_NOVO_SAL
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID=P_ID_FUNC;

RETURN V_NOVO_SAL;

END;

SELECT A.FIRST_NAME, A.SALARY, FN_AUMENTO(10,A.EMPLOYEE_ID) AS NOVO_SALARIO
FROM HR.EMPLOYEES A;

    