-- FUNÇÃO COMO BLOCO ANONIMO CONCLUIDO.
-- PEGAR DOIS NÚMEROS E DIZER QUAL É O MAIOR.

SET SERVEROUTPUT ON

DECLARE
    PNUM1 NUMBER;
    PNUM2 NUMBER;
    PNUM_MAX NUMBER;
    
FUNCTION FN_MAX_VAL(
    PNUM1 IN NUMBER,
    PNUM2 IN NUMBER)
RETURN NUMBER
AS
PNUM_MAX NUMBER;
BEGIN
    IF PNUM1 > PNUM2 THEN
        PNUM_MAX := PNUM1;
    ELSE
        PNUM_MAX := PNUM2;
    END IF;
    RETURN PNUM_MAX;
END;

BEGIN
    PNUM1 := 70;
    PNUM2 := 85;
    PNUM_MAX := FN_MAX_VAL (PNUM1, PNUM2);
    DBMS_OUTPUT.PUT_LINE('O MAIOR VALOR ENTRE '||PNUM1||' E '||PNUM2||' É '||PNUM_MAX);
END;

