--criando função para retornar a quantidade de salarios minimos que a pessoa recebe.
CREATE OR REPLACE FUNCTION FN_SAL_MIN (P_SAL IN NUMBER)
RETURN NUMBER
IS
V_QTD_SAL_MIN   NUMBER(10,2);
BEGIN
    V_QTD_SAL_MIN := P_SAL/954;
    RETURN V_QTD_SAL_MIN;
END;

-- USANDO A FUNÇÃO
SELECT A.FIRST_NAME, A.SALARY, FN_SAL_MIN(A.SALARY) AS QTD_MIN
FROM HR.EMPLOYEES A
ORDER BY A.SALARY DESC;