CREATE OR REPLACE FUNCTION FN_CALCULO(PART1 IN NUMBER, PART2 IN NUMBER, RES OUT NUMBER)
RETURN NUMBER
IS
AUX NUMBER:=0;
BEGIN
    RES := PART1+PART2;
    AUX := RES+100;
    RETURN(AUX);
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO: '||SQLERRM);
END;

--TESTANDO
DECLARE
RES0 NUMBER := 0;
RES1 NUMBER := 0;
BEGIN
    RES0 := FN_CALCULO(6, 14, RES1);
    DBMS_OUTPUT.PUT_LINE('O RESULTADO É: '||RES0||' E '||RES1);
END;