-- sem parametros
CREATE OR REPLACE FUNCTION FN_NOME
    RETURN VARCHAR IS
    V_NOME VARCHAR(20);
BEGIN
    SELECT A.FIRST_NAME
    INTO V_NOME
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID = 100;
    
    RETURN V_NOME;
END;

-- SELECIONAR A FUNÇÃO
SELECT FN_NOME FROM DUAL;