SET SERVEROUTPUT ON
ACCEPT VDIGITADO PROMPT 'DIGITE A TABUADA'
DECLARE
    VTAB INT;
    VLIMIT INT DEFAULT 1;
BEGIN
    VTAB:=&VDIGITADO;
    WHILE VLIMIT <=10 LOOP
        DBMS_OUTPUT.PUT_LINE(VLIMIT||' X '||VTAB||' = '||VLIMIT*VTAB);
        --CONTADOR
        VLIMIT:=VLIMIT+1;
    END LOOP;
END;

-- EXEMPLO USANDO ESTRUTURA WHILE COM SAIDA EXIT PARA INTERRUPÇÃO
ACCEPT VDIGITADO PROMPT 'DIGITE UM VALOR'
DECLARE
    VTAB INT;
    VLIMIT INT DEFAULT 1;
BEGIN
    VTAB:=&VDIGITADO;
    WHILE VLIMIT <=10 LOOP
        DBMS_OUTPUT.PUT_LINE(VLIMIT||' X '||VTAB||' = '||VLIMIT*VTAB);
        VLIMIT:=VLIMIT+1;
        EXIT WHEN VLIMIT>5;
    END LOOP;
END;