--EXEMPLO DE LOOP
SET SERVEROUTPUT ON
DECLARE
    P_VALOR NUMBER := 0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('DENTRO DO LOOP O VALOR É IGUAL '||TO_CHAR(P_VALOR));
        P_VALOR := P_VALOR +1;
        CONTINUE WHEN p_valor < 5;
        DBMS_OUTPUT.PUT_LINE('APÓS A CLAUSULA CONTINUE O VALOR É IGUAL '||TO_CHAR(P_VALOR));
    EXIT WHEN P_VALOR = 5;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('APÓS O LOOP O VALOR É IGUAL '||TO_CHAR(P_VALOR));
END;

-- OUTRO EXEMPLO
DECLARE
    VALOR NUMBER := 0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR APRENSENTADO NO INTERIOR DO LOOP É IGUAL A: '||TO_CHAR(VALOR));
        VALOR := VALOR +1;
        IF VALOR < 15 THEN
            CONTINUE;
        END IF;
        DBMS_OUTPUT.PUT_LINE('DENTRO DO LOOP O VALOR É IGUAL '||TO_CHAR(VALOR));
        EXIT WHEN VALOR > 15;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Após o loop, o valor é igual a: '||to_char(valor));
END;