SET SERVEROUTPUT ON
ACCEPT VDIGITADO PROMPT 'DIGITE A TABUADA'
DECLARE
    VTAB INT;
    VLIMIT INT DEFAULT 1;
BEGIN
    VTAB:=&VDIGITADO;
    WHILE VLIMIT <=10 LOOP
        DBMS_OUTPUT.PUT_LINE(VLIMIT||' X '||VTAB||' = '||VLIMIT*VTAB);
        VLIMIT:=VLIMIT+1;
    END LOOP;
END;