--PARA IMPRIMIR O VALOR DESEJADO
SET SERVEROUTPUT ON

--DECLARANDO AS VARIAVEIS
DECLARE
-- NOME DA VARIAVEL E O TIPO DELA
V_TOTAL_SAL NUMBER  (10,2);
V_DEPTO NUMBER;
V_QTD   INT;

--BLOCO OBRIGATORIO
BEGIN
--ATRIBUINDO VALOR A VARIAVEL
V_DEPTO := 100;
--SELECIONANDO VALORES E ATRIBUINDO DENTRO DAS VARIAVEIS
SELECT SUM(A.SALARY), COUNT(*) QTD
    INTO V_TOTAL_SAL, V_QTD
    FROM HR.EMPLOYEES A WHERE A.DEPARTMENT_ID=V_DEPTO;
    
DBMS_OUTPUT.PUT_LINE('TOTAL DE SALARIO DEPTO '||V_DEPTO||' É '||V_TOTAL_SAL);
DBMS_OUTPUT.PUT_LINE('TOTAL DE COLABORADORES '||V_QTD);
DBMS_OUTPUT.PUT_LINE('MÉDIA DE SALARIO DESSE DEPTO '||ROUND(V_TOTAL_SAL/V_QTD,2));

END;