-- CURSOR IMPLICITO ORACLE
SET SERVEROUTPUT ON
BEGIN 
FOR VFUNC IN (SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM HR.EMPLOYEES A
ORDER BY A.SALARY DESC)

LOOP

-- IMPRIME DADOS EXTRAIDOS NA TELA
dbms_output.put_line(VFUNC.EMPLOYEE_ID||' - '||VFUNC.FIRST_NAME||' - '||VFUNC.SALARY);
END LOOP;
END;