SET SERVEROUTPUT ON
DECLARE
TYPE TFUNC IS RECORD(
V_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE,
V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE,
V_SALARIO HR.EMPLOYEES.SALARY%TYPE);

VFUNC TFUNC;

CURSOR CS_FUNC IS
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM HR.EMPLOYEES A
ORDER BY A.SALARY DESC;

BEGIN

IF NOT CS_FUNC%ISOPEN THEN
OPEN CS_FUNC;
END IF;

LOOP

FETCH CS_FUNC INTO VFUNC;

EXIT WHEN CS_FUNC%NOTFOUND;

DBMS_OUTPUT.PUT_LINE(VFUNC.V_ID||' - '||VFUNC.V_NOME||' - '||VFUNC.V_SALARIO);
END LOOP;

CLOSE CS_FUNC;

END;