SET SERVEROUTPUT ON

DECLARE
-- DECLARAÇÃO DE VARIAVEIS
V_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE;
V_SALARIO HR.EMPLOYEES.SALARY%TYPE;
-- DECLARAÇÃO DOS CURSORES
CURSOR CS_SALARIO_TOP_10 IS
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM HR.EMPLOYEES A
ORDER BY A.SALARY DESC;
-- INICIO
BEGIN
-- ABRE O CURSOR
OPEN CS_SALARIO_TOP_10;
-- EXECUTA O LOOP COM 10 CICLOS
FOR i IN 1..10 LOOP
    -- EXTRAI DADOS O REGISTRO CORRENTE DO CURSOR E AVANÇA PARA O PROXIMO
    FETCH CS_SALARIO_TOP_10 INTO V_ID, V_NOME, V_SALARIO;
    -- IMPRIME DADOS EXTRAIDOS NA TELA
    DBMS_OUTPUT.PUT_LINE(V_ID||' - '||V_NOME||' - '||V_SALARIO);
END LOOP;
-- FECHA O CURSOR
CLOSE CS_SALARIO_TOP_10;
END;
/
