SET SERVEROUTPUT ON

DECLARE

V_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
V_NOME HR.EMPLOYEES.FIRST_NAME%TYPE;
V_SALARIO HR.EMPLOYEES.SALARY%TYPE;

-- DECLARANDO CURSOR
CURSOR CS_TOP_10 IS
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM HR.EMPLOYEES A
ORDER BY A.SALARY DESC;

BEGIN

-- ABRE O CURSOR SE AINDA NÃO TIVER ABERTO
IF NOT CS_TOP_10%ISOPEN THEN
    OPEN CS_TOP_10;
END IF;
-- EXECUTA UM LOOP DE 10 CICLOS
FOR I IN 1..10 LOOP
    -- EXTRAI DADOS O REGISTRO CORRENTE DO CURSOR E AVANÇA PARA O PROXIMO
    FETCH CS_TOP_10 INTO V_ID, V_NOME, V_SALARIO;
    -- IMPRIME DADOS EXTRAIDOS NA TELA
    DBMS_OUTPUT.PUT_LINE(I||' - '||V_ID||' - '||V_NOME||' - '||V_SALARIO);
END LOOP;
CLOSE CS_TOP_10;
END;
/

