CREATE OR REPLACE PROCEDURE PROC_INFO_DEPTO
IS
    CURSOR CRS_DEPTO
    IS
        SELECT A.DEPARTMENT_ID, B.DEPARTMENT_NAME, SUM(A.SALARY) SALARIO
        FROM HR.EMPLOYEES A
        INNER JOIN HR.DEPARTMENTS B
        ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
        GROUP BY A.DEPARTMENT_ID, B.DEPARTMENT_NAME
        ORDER BY SALARIO DESC;
        
        FUN_DEPTO CRS_DEPTO%ROWTYPE;

    BEGIN
        FOR FUN_DEPTO IN CRS_DEPTO LOOP
            DBMS_OUTPUT.PUT_LINE('ID DO DEPARTMAMENTO: '||FUN_DEPTO.DEPARTMENT_ID||' - NOME DO DEPARTMENTO: '||FUN_DEPTO.DEPARTMENT_NAME||' - SALARIO TOTAL DO DEPARTMENTO: '||FUN_DEPTO.SALARIO);
        END LOOP;
    
    EXCEPTION 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO: '||SQLERRM);
END;
        
        
-- EXECUTANDO
EXECUTE proc_info_depto;