CREATE OR REPLACE PROCEDURE PRC_DETALHE_DOS_FUNCIONARIOS
IS
    CURSOR EMP_CUR
    IS
        SELECT FIRST_NAME, LAST_NAME, SALARY FROM
        HR.EMPLOYEES;
        EMP_REC EMP_CUR%ROWTYPE;
    BEGIN
        FOR EMP_REC IN EMP_CUR
        LOOP
            DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------- ');
            DBMS_OUTPUT.PUT_LINE('NOME DO FUNCIONARIO '||EMP_REC.FIRST_NAME);
            DBMS_OUTPUT.PUT_LINE('SOBRENOME DO FUNCIONARIO '||EMP_REC.LAST_NAME);
            DBMS_OUTPUT.PUT_LINE('SALARIO DO FUNCIONARIO '||EMP_REC.SALARY);
            DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------- ');
        END LOOP;
    END;
    
-- EXECUTANDO PROCEDURE COMO BLOCO ANONIMO
SET SERVEROUTPUT ON
BEGIN
    PRC_DETALHE_DOS_FUNCIONARIOS;
END;

-- OUTRA FORMA DE EXECUÇÃO
EXECUTE prc_detalhe_dos_funcionarios;