-- Exibe dados de um funcionario da tabela 'employees', schema 'hr'
-- & comercial na variavel para abrir prompt e inserir valor

SET SERVEROUTPUT ON

DECLARE
-- DEFINIÇÃO DE TIPO DE VARIAVEIS
TYPE TFUNCIONARIO IS RECORD(
    NOME VARCHAR2(40),
    DEPTO VARCHAR2(20),
    SALARIO NUMBER(10,2)
);
--DECLARAÇÃO DE VARIAVEIS
VFUNC TFUNCIONARIO;
BEGIN
-- ATRIBUIR VALOR PARA O REGISTRO VPRODUTO
SELECT A.FIRST_NAME, A.DEPARTMENT_ID, A.SALARY
INTO VFUNC.NOME, VFUNC.DEPTO, VFUNC.SALARIO
FROM HR.EMPLOYEES A
WHERE A.EMPLOYEE_ID = 102;
-- IMPRIMIR NA TELA OS DADOS RECUPERADOS
DBMS_OUTPUT.PUT_LINE('NOME DO PRODUTO: '||VFUNC.NOME||CHR(10)||
'DEPTO: '||VFUNC.DEPTO||CHR(10)||'SALARIO: '||TO_CHAR(VFUNC.SALARIO));

END;