CREATE TABLE EMPREGADOS (
    CODIGO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2 (20),
    SALARIO DECIMAL(10,2)
);

CREATE TABLE LOG_SALARIO (
    CODIGO INT,
    SALARIO_ANTERIOR DECIMAL(10,2),
    SALARIO_ATUAL DECIMAL(10,2),
    DATA_ALTERACAO DATE,
    USUARIO VARCHAR2(20),
    OPERACAO VARCHAR2(10)
);

CREATE OR REPLACE TRIGGER TRG_SALARIO_AUD
AFTER INSERT ON EMPREGADOS
FOR EACH ROW
BEGIN
    INSERT INTO LOG_SALARIO(CODIGO, SALARIO_ANTERIOR, SALARIO_ATUAL, DATA_ALTERACAO, USUARIO, OPERACAO)
    VALUES (:NEW.CODIGO, :OLD.SALARIO, :NEW.SALARIO, SYSDATE, USER,'');
END;

-- TESTE INSERT
INSERT INTO EMPREGADOS VALUES (1,'Peter',2999);
INSERT INTO EMPREGADOS VALUES (2,'John',3499);

SELECT * FROM EMPREGADOS;
SELECT * FROM LOG_SALARIO;

-- TESTE UPDATE
UPDATE EMPREGADOS SET SALARIO = SALARIO*1.10 WHERE CODIGO = '1';

-- DESABILITANDO TRIGGER
ALTER TRIGGER TRG_SALARIO_AUD DISABLE;
-- HABILITANDO A TRIGGER
ALTER TRIGGER TRG_SALARIO_AUD ENABLE;