CREATE TABLE EMPREGADOS (
    CODIGO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2 (20),
    SALARIO DECIMAL(10,2)
);

CREATE TABLE LOG_SALARIO (
    CODIGO INT,
    SALARIO_ANTERIOR DECIMAL(10,2),
    SALARIO_ATUAL DECIMAL(10,2),
    DATA_ALTERACAO DATE,
    USUARIO VARCHAR2(20),
    OPERACAO VARCHAR2(10)
);

CREATE OR REPLACE TRIGGER TRG_SALARIO_AUD
AFTER INSERT ON EMPREGADOS
FOR EACH ROW
BEGIN
    INSERT INTO LOG_SALARIO(CODIGO, SALARIO_ANTERIOR, SALARIO_ATUAL, DATA_ALTERACAO, USUARIO, OPERACAO)
    VALUES (:NEW.CODIGO, :OLD.SALARIO, :NEW.SALARIO, SYSDATE, USER,'');