-- EXIBE DADOS DE UM FUNCIONARIO DA TABELA 'EMPLOYEES', SCHEMA 'HR'
-- & --> "E" COMERCIAL NA VARIAVEL PARA PL/SQL PEDIR VALOR PARA VARIAVEL VIA PROMPT
-- USANDO TYPE

SET SERVEROUTPUT ON
DECLARE
    V_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    V_SAL HR.EMPLOYEES.SALARY%TYPE;
    
BEGIN
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
    INTO V_ID, V_NAME, V_SAL
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID=&EMP_ID;
    
    DBMS_OUTPUT.PUT_LINE ('----------------------------------');
    DBMS_OUTPUT.PUT_LINE ('ID: '||V_ID);
    DBMS_OUTPUT.PUT_LINE ('NAME: '||V_NAME);
    DBMS_OUTPUT.PUT_LINE ('SALARY: '||V_SAL);
    
END;

-- USANDO ROWTYPE
SET SERVEROUTPUT ON
DECLARE
    V_EMP HR.EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO V_EMP
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID=&EMP_ID;
    
    DBMS_OUTPUT.PUT_LINE ('----------------------------------');
    DBMS_OUTPUT.PUT_LINE ('ID: '||V_EMP.EMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE ('NAME: '||V_EMP.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE ('SALARY: '||V_EMP.SALARY);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Matricula n�o existe');
END;