SET SERVEROUTPUT ON

DECLARE
    V_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    V_SALARY HR.EMPLOYEES.SALARY%TYPE;

BEGIN
    SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
    INTO V_ID, V_NAME, V_SALARY
    FROM HR.EMPLOYEES A
    WHERE A.EMPLOYEE_ID = &EMP_ID;

    DBMS_OUTPUT.PUT_LINE('-----------------------------');
    DBMS_OUTPUT.PUT_LINE('ID: '||TO_CHAR(V_ID));
    DBMS_OUTPUT.PUT_LINE('NOME: '||TO_CHAR(V_NAME));
    DBMS_OUTPUT.PUT_LINE('SALARIO :'||TO_CHAR(V_SALARY));
    
END;
