--CRIANDO A VIEW

CREATE OR REPLACE VIEW V_FUNC_DEPTO
AS
SELECT  A.EMPLOYEE_ID,
        A.FIRST_NAME,
        A.SALARY,
        A.DEPARTMENT_ID,
        B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
INNER JOIN HR.DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID;

--USANDO A VIEW
SELECT * FROM V_FUNC_DEPTO
WHERE DEPARTMENT_ID = '20';

--ALTERANDO A VIEW
CREATE OR REPLACE VIEW V_FUNC_DEPTO
AS
SELECT  A.FIRST_NAME,
        A.LAST_NAME,
        A.SALARY,
        A.DEPARTMENT_ID,
        B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
INNER JOIN HR.DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID;

--PAISES, LOCATION, E REGIOES
CREATE OR REPLACE VIEW V_PAIS_REGIAO
AS
SELECT  A.COUNTRY_ID,
        A.COUNTRY_NAME,
        A.REGION_ID,
        B.REGION_NAME
FROM HR.COUNTRIES A
INNER JOIN HR.REGIONS B
ON A.REGION_ID=B.REGION_ID;

--USANDO A VIEW
SELECT * FROM v_pais_regiao
WHERE REGION_NAME <>'Europe';

--Reutilizando a view
Select region_name, count(*) qtd
from v_pais_regiao
group by region_name;


-- criando view
CREATE OR REPLACE VIEW V_PAIS_LOCAL
AS
SELECT  A.LOCATION_ID,
        A.CITY,
        B.COUNTRY_NAME
FROM HR.LOCATIONS A
INNER JOIN V_PAIS_REGIAO B
ON A.COUNTRY_ID=B.COUNTRY_ID;

-- UTILIZANDO A VIEW
SELECT * FROM V_PAIS_LOCAL WHERE COUNTRY_NAME<>'Italy';

-- CRIANDO VIEW COM UNION ALL
CREATE OR REPLACE VIEW V_DEPTO_UNION
AS
SELECT  A.EMPLOYEE_ID,
        A.FIRST_NAME,
        A.SALARY,
        A.DEPARTMENT_ID,
        B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
INNER JOIN HR.DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
WHERE A.DEPARTMENT_ID ='10'

UNION ALL

SELECT  A.EMPLOYEE_ID,
        A.FIRST_NAME,
        A.SALARY,
        A.DEPARTMENT_ID,
        B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
INNER JOIN HR.DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
WHERE A.DEPARTMENT_ID ='20'

UNION ALL

SELECT  A.EMPLOYEE_ID,
        A.FIRST_NAME,
        A.SALARY,
        A.DEPARTMENT_ID,
        B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
INNER JOIN HR.DEPARTMENTS B
ON A.DEPARTMENT_ID=B.DEPARTMENT_ID
WHERE A.DEPARTMENT_ID NOT IN ('10', '20');


-- UTILIZANDO A VIEW
SELECT * FROM v_depto_union;


